### ISSUE TITLE
Patch releases are incorrectly marked as latest release

### ISSUE THREAD

**Issue by dprotaso** [knative/infra#201]
When a patch release (for an older release branch) occurs the hack scripts are marking that as the latest release.

Only patch releases from the latest branch should be marked as the latest release.

**Comment by dprotaso** [comment]
eg. when serving cut two point releases for two branches (release-1.10, release-1.11) the release-1.10 branch finished last.

SInce release-1.10 finished last the point release was marked as the latest.

So we have

release order by time
v1.10.0
v1.11.0
v1.11.1
v1.10.0 <-- marked as latest


But I would expect v1.11.1 to be the latest release. I had to manually update this.

**Comment by kvmware** [comment]
Looks like that hub tool does not have any way to specify a latest (https://hub.github.com/hub-release.1.html) and whatever was touched last becomes the latest. This would have to be tested with maybe a `hub edit` <current>, after a dot for a older release is done. Otherwise, we might have to switch over to `gh` cli tool (https://cli.github.com/manual/gh_release_create) that allows a `--latest` flag.
